inline void point_to_target_hpp_tait_bryan_wc(double &delta_x, double &delta_y, double &delta_z, double tx_1, double ty_1, double tz_1, double om_1, double fi_1, double ka_1, double tx_c, double ty_c, double tz_c, double om_c, double fi_c, double ka_c, double x_1, double y_1, double z_1, double x_t, double y_t, double z_t)
{delta_x = -tx_1 - tx_c*cos(fi_1)*cos(ka_1) + ty_c*sin(ka_1)*cos(fi_1) - tz_c*sin(fi_1) - x_1*(-(sin(fi_c)*sin(om_c)*cos(ka_c) + sin(ka_c)*cos(om_c))*sin(ka_1)*cos(fi_1) + (-sin(fi_c)*cos(ka_c)*cos(om_c) + sin(ka_c)*sin(om_c))*sin(fi_1) + cos(fi_1)*cos(fi_c)*cos(ka_1)*cos(ka_c)) + x_t - y_1*(-(-sin(fi_c)*sin(ka_c)*sin(om_c) + cos(ka_c)*cos(om_c))*sin(ka_1)*cos(fi_1) + (sin(fi_c)*sin(ka_c)*cos(om_c) + sin(om_c)*cos(ka_c))*sin(fi_1) - sin(ka_c)*cos(fi_1)*cos(fi_c)*cos(ka_1)) - z_1*(sin(fi_1)*cos(fi_c)*cos(om_c) + sin(fi_c)*cos(fi_1)*cos(ka_1) + sin(ka_1)*sin(om_c)*cos(fi_1)*cos(fi_c));
delta_y = -tx_c*(sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1)) - ty_1 - ty_c*(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1)) + tz_c*sin(om_1)*cos(fi_1) - x_1*((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_c)*sin(om_c)*cos(ka_c) + sin(ka_c)*cos(om_c)) + (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*cos(fi_c)*cos(ka_c) - (-sin(fi_c)*cos(ka_c)*cos(om_c) + sin(ka_c)*sin(om_c))*sin(om_1)*cos(fi_1)) - y_1*((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(-sin(fi_c)*sin(ka_c)*sin(om_c) + cos(ka_c)*cos(om_c)) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*sin(ka_c)*cos(fi_c) - (sin(fi_c)*sin(ka_c)*cos(om_c) + sin(om_c)*cos(ka_c))*sin(om_1)*cos(fi_1)) + y_t - z_1*(-(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*sin(om_c)*cos(fi_c) + (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*sin(fi_c) - sin(om_1)*cos(fi_1)*cos(fi_c)*cos(om_c));
delta_z = -tx_c*(-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1)) - ty_c*(sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1)) - tz_1 - tz_c*cos(fi_1)*cos(om_1) - x_1*((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_c)*sin(om_c)*cos(ka_c) + sin(ka_c)*cos(om_c)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*cos(fi_c)*cos(ka_c) + (-sin(fi_c)*cos(ka_c)*cos(om_c) + sin(ka_c)*sin(om_c))*cos(fi_1)*cos(om_1)) - y_1*((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(-sin(fi_c)*sin(ka_c)*sin(om_c) + cos(ka_c)*cos(om_c)) - (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*sin(ka_c)*cos(fi_c) + (sin(fi_c)*sin(ka_c)*cos(om_c) + sin(om_c)*cos(ka_c))*cos(fi_1)*cos(om_1)) - z_1*(-(sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*sin(om_c)*cos(fi_c) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*sin(fi_c) + cos(fi_1)*cos(fi_c)*cos(om_1)*cos(om_c)) + z_t;
}
inline void point_to_target_hpp_tait_bryan_wc_jacobian(Eigen::Matrix<double, 3, 12, Eigen::RowMajor> &j, double tx_1, double ty_1, double tz_1, double om_1, double fi_1, double ka_1, double tx_c, double ty_c, double tz_c, double om_c, double fi_c, double ka_c, double x_1, double y_1, double z_1, double x_t, double y_t, double z_t)
{j.coeffRef(0,0) = -1;
j.coeffRef(0,1) = 0;
j.coeffRef(0,2) = 0;
j.coeffRef(0,3) = 0;
j.coeffRef(0,4) = tx_c*sin(fi_1)*cos(ka_1) - ty_c*sin(fi_1)*sin(ka_1) - tz_c*cos(fi_1) - x_1*(-(-sin(fi_c)*sin(om_c)*cos(ka_c) - sin(ka_c)*cos(om_c))*sin(fi_1)*sin(ka_1) + (-sin(fi_c)*cos(ka_c)*cos(om_c) + sin(ka_c)*sin(om_c))*cos(fi_1) - sin(fi_1)*cos(fi_c)*cos(ka_1)*cos(ka_c)) - y_1*(-(sin(fi_c)*sin(ka_c)*sin(om_c) - cos(ka_c)*cos(om_c))*sin(fi_1)*sin(ka_1) + (sin(fi_c)*sin(ka_c)*cos(om_c) + sin(om_c)*cos(ka_c))*cos(fi_1) + sin(fi_1)*sin(ka_c)*cos(fi_c)*cos(ka_1)) - z_1*(-sin(fi_1)*sin(fi_c)*cos(ka_1) - sin(fi_1)*sin(ka_1)*sin(om_c)*cos(fi_c) + cos(fi_1)*cos(fi_c)*cos(om_c));
j.coeffRef(0,5) = tx_c*sin(ka_1)*cos(fi_1) + ty_c*cos(fi_1)*cos(ka_1) - x_1*((-sin(fi_c)*sin(om_c)*cos(ka_c) - sin(ka_c)*cos(om_c))*cos(fi_1)*cos(ka_1) - sin(ka_1)*cos(fi_1)*cos(fi_c)*cos(ka_c)) - y_1*((sin(fi_c)*sin(ka_c)*sin(om_c) - cos(ka_c)*cos(om_c))*cos(fi_1)*cos(ka_1) + sin(ka_1)*sin(ka_c)*cos(fi_1)*cos(fi_c)) - z_1*(-sin(fi_c)*sin(ka_1)*cos(fi_1) + sin(om_c)*cos(fi_1)*cos(fi_c)*cos(ka_1));
j.coeffRef(0,6) = -cos(fi_1)*cos(ka_1);
j.coeffRef(0,7) = sin(ka_1)*cos(fi_1);
j.coeffRef(0,8) = -sin(fi_1);
j.coeffRef(0,9) = -x_1*((sin(fi_c)*sin(om_c)*cos(ka_c) + sin(ka_c)*cos(om_c))*sin(fi_1) + (-sin(fi_c)*cos(ka_c)*cos(om_c) + sin(ka_c)*sin(om_c))*sin(ka_1)*cos(fi_1)) - y_1*((-sin(fi_c)*sin(ka_c)*sin(om_c) + cos(ka_c)*cos(om_c))*sin(fi_1) + (sin(fi_c)*sin(ka_c)*cos(om_c) + sin(om_c)*cos(ka_c))*sin(ka_1)*cos(fi_1)) - z_1*(-sin(fi_1)*sin(om_c)*cos(fi_c) + sin(ka_1)*cos(fi_1)*cos(fi_c)*cos(om_c));
j.coeffRef(0,10) = -x_1*(-sin(fi_1)*cos(fi_c)*cos(ka_c)*cos(om_c) - sin(fi_c)*cos(fi_1)*cos(ka_1)*cos(ka_c) - sin(ka_1)*sin(om_c)*cos(fi_1)*cos(fi_c)*cos(ka_c)) - y_1*(sin(fi_1)*sin(ka_c)*cos(fi_c)*cos(om_c) + sin(fi_c)*sin(ka_c)*cos(fi_1)*cos(ka_1) + sin(ka_1)*sin(ka_c)*sin(om_c)*cos(fi_1)*cos(fi_c)) - z_1*(-sin(fi_1)*sin(fi_c)*cos(om_c) - sin(fi_c)*sin(ka_1)*sin(om_c)*cos(fi_1) + cos(fi_1)*cos(fi_c)*cos(ka_1));
j.coeffRef(0,11) = -x_1*((sin(fi_c)*sin(ka_c)*sin(om_c) - cos(ka_c)*cos(om_c))*sin(ka_1)*cos(fi_1) + (sin(fi_c)*sin(ka_c)*cos(om_c) + sin(om_c)*cos(ka_c))*sin(fi_1) - sin(ka_c)*cos(fi_1)*cos(fi_c)*cos(ka_1)) - y_1*((sin(fi_c)*sin(om_c)*cos(ka_c) + sin(ka_c)*cos(om_c))*sin(ka_1)*cos(fi_1) + (sin(fi_c)*cos(ka_c)*cos(om_c) - sin(ka_c)*sin(om_c))*sin(fi_1) - cos(fi_1)*cos(fi_c)*cos(ka_1)*cos(ka_c));
j.coeffRef(1,0) = 0;
j.coeffRef(1,1) = -1;
j.coeffRef(1,2) = 0;
j.coeffRef(1,3) = -tx_c*(sin(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_1)) - ty_c*(-sin(fi_1)*sin(ka_1)*cos(om_1) - sin(om_1)*cos(ka_1)) + tz_c*cos(fi_1)*cos(om_1) - x_1*((-sin(fi_1)*sin(ka_1)*cos(om_1) - sin(om_1)*cos(ka_1))*(sin(fi_c)*sin(om_c)*cos(ka_c) + sin(ka_c)*cos(om_c)) + (sin(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_1))*cos(fi_c)*cos(ka_c) + (sin(fi_c)*cos(ka_c)*cos(om_c) - sin(ka_c)*sin(om_c))*cos(fi_1)*cos(om_1)) - y_1*((-sin(fi_1)*sin(ka_1)*cos(om_1) - sin(om_1)*cos(ka_1))*(-sin(fi_c)*sin(ka_c)*sin(om_c) + cos(ka_c)*cos(om_c)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*sin(ka_c)*cos(fi_c) + (-sin(fi_c)*sin(ka_c)*cos(om_c) - sin(om_c)*cos(ka_c))*cos(fi_1)*cos(om_1)) - z_1*((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*sin(om_c)*cos(fi_c) + (sin(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_1))*sin(fi_c) - cos(fi_1)*cos(fi_c)*cos(om_1)*cos(om_c));
j.coeffRef(1,4) = -tx_c*sin(om_1)*cos(fi_1)*cos(ka_1) + ty_c*sin(ka_1)*sin(om_1)*cos(fi_1) - tz_c*sin(fi_1)*sin(om_1) - x_1*(-(sin(fi_c)*sin(om_c)*cos(ka_c) + sin(ka_c)*cos(om_c))*sin(ka_1)*sin(om_1)*cos(fi_1) - (sin(fi_c)*cos(ka_c)*cos(om_c) - sin(ka_c)*sin(om_c))*sin(fi_1)*sin(om_1) + sin(om_1)*cos(fi_1)*cos(fi_c)*cos(ka_1)*cos(ka_c)) - y_1*(-(-sin(fi_c)*sin(ka_c)*sin(om_c) + cos(ka_c)*cos(om_c))*sin(ka_1)*sin(om_1)*cos(fi_1) - (-sin(fi_c)*sin(ka_c)*cos(om_c) - sin(om_c)*cos(ka_c))*sin(fi_1)*sin(om_1) - sin(ka_c)*sin(om_1)*cos(fi_1)*cos(fi_c)*cos(ka_1)) - z_1*(sin(fi_1)*sin(om_1)*cos(fi_c)*cos(om_c) + sin(fi_c)*sin(om_1)*cos(fi_1)*cos(ka_1) + sin(ka_1)*sin(om_1)*sin(om_c)*cos(fi_1)*cos(fi_c));
j.coeffRef(1,5) = -tx_c*(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1)) - ty_c*(-sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1)) - x_1*((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*cos(fi_c)*cos(ka_c) + (-sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1))*(sin(fi_c)*sin(om_c)*cos(ka_c) + sin(ka_c)*cos(om_c))) - y_1*((sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1))*sin(ka_c)*cos(fi_c) + (-sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1))*(-sin(fi_c)*sin(ka_c)*sin(om_c) + cos(ka_c)*cos(om_c))) - z_1*((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*sin(fi_c) + (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*sin(om_c)*cos(fi_c));
j.coeffRef(1,6) = -sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1);
j.coeffRef(1,7) = sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1);
j.coeffRef(1,8) = sin(om_1)*cos(fi_1);
j.coeffRef(1,9) = -x_1*((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_c)*cos(ka_c)*cos(om_c) - sin(ka_c)*sin(om_c)) + (-sin(fi_c)*sin(om_c)*cos(ka_c) - sin(ka_c)*cos(om_c))*sin(om_1)*cos(fi_1)) - y_1*((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(-sin(fi_c)*sin(ka_c)*cos(om_c) - sin(om_c)*cos(ka_c)) + (sin(fi_c)*sin(ka_c)*sin(om_c) - cos(ka_c)*cos(om_c))*sin(om_1)*cos(fi_1)) - z_1*((sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1))*cos(fi_c)*cos(om_c) + sin(om_1)*sin(om_c)*cos(fi_1)*cos(fi_c));
j.coeffRef(1,10) = -x_1*((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*sin(om_c)*cos(fi_c)*cos(ka_c) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*sin(fi_c)*cos(ka_c) + sin(om_1)*cos(fi_1)*cos(fi_c)*cos(ka_c)*cos(om_c)) - y_1*(-(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*sin(ka_c)*sin(om_c)*cos(fi_c) - (-sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1))*sin(fi_c)*sin(ka_c) - sin(ka_c)*sin(om_1)*cos(fi_1)*cos(fi_c)*cos(om_c)) - z_1*(-(sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1))*sin(fi_c)*sin(om_c) + (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*cos(fi_c) + sin(fi_c)*sin(om_1)*cos(fi_1)*cos(om_c));
j.coeffRef(1,11) = -x_1*((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(-sin(fi_c)*sin(ka_c)*sin(om_c) + cos(ka_c)*cos(om_c)) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*sin(ka_c)*cos(fi_c) + (-sin(fi_c)*sin(ka_c)*cos(om_c) - sin(om_c)*cos(ka_c))*sin(om_1)*cos(fi_1)) - y_1*((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(-sin(fi_c)*sin(om_c)*cos(ka_c) - sin(ka_c)*cos(om_c)) + (-sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1))*cos(fi_c)*cos(ka_c) + (-sin(fi_c)*cos(ka_c)*cos(om_c) + sin(ka_c)*sin(om_c))*sin(om_1)*cos(fi_1));
j.coeffRef(2,0) = 0;
j.coeffRef(2,1) = 0;
j.coeffRef(2,2) = -1;
j.coeffRef(2,3) = -tx_c*(sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1)) - ty_c*(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1)) + tz_c*sin(om_1)*cos(fi_1) - x_1*((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_c)*sin(om_c)*cos(ka_c) + sin(ka_c)*cos(om_c)) + (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*cos(fi_c)*cos(ka_c) - (-sin(fi_c)*cos(ka_c)*cos(om_c) + sin(ka_c)*sin(om_c))*sin(om_1)*cos(fi_1)) - y_1*((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(-sin(fi_c)*sin(ka_c)*sin(om_c) + cos(ka_c)*cos(om_c)) + (-sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1))*sin(ka_c)*cos(fi_c) - (sin(fi_c)*sin(ka_c)*cos(om_c) + sin(om_c)*cos(ka_c))*sin(om_1)*cos(fi_1)) - z_1*((sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1))*sin(om_c)*cos(fi_c) + (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*sin(fi_c) - sin(om_1)*cos(fi_1)*cos(fi_c)*cos(om_c));
j.coeffRef(2,4) = tx_c*cos(fi_1)*cos(ka_1)*cos(om_1) - ty_c*sin(ka_1)*cos(fi_1)*cos(om_1) + tz_c*sin(fi_1)*cos(om_1) - x_1*((sin(fi_c)*sin(om_c)*cos(ka_c) + sin(ka_c)*cos(om_c))*sin(ka_1)*cos(fi_1)*cos(om_1) - (-sin(fi_c)*cos(ka_c)*cos(om_c) + sin(ka_c)*sin(om_c))*sin(fi_1)*cos(om_1) - cos(fi_1)*cos(fi_c)*cos(ka_1)*cos(ka_c)*cos(om_1)) - y_1*((-sin(fi_c)*sin(ka_c)*sin(om_c) + cos(ka_c)*cos(om_c))*sin(ka_1)*cos(fi_1)*cos(om_1) - (sin(fi_c)*sin(ka_c)*cos(om_c) + sin(om_c)*cos(ka_c))*sin(fi_1)*cos(om_1) + sin(ka_c)*cos(fi_1)*cos(fi_c)*cos(ka_1)*cos(om_1)) - z_1*(-sin(fi_1)*cos(fi_c)*cos(om_1)*cos(om_c) - sin(fi_c)*cos(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_c)*cos(fi_1)*cos(fi_c)*cos(om_1));
j.coeffRef(2,5) = -tx_c*(sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1)) - ty_c*(sin(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_1)) - x_1*((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*cos(fi_c)*cos(ka_c) + (sin(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_1))*(sin(fi_c)*sin(om_c)*cos(ka_c) + sin(ka_c)*cos(om_c))) - y_1*((-sin(fi_1)*sin(ka_1)*cos(om_1) - sin(om_1)*cos(ka_1))*sin(ka_c)*cos(fi_c) + (sin(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_1))*(-sin(fi_c)*sin(ka_c)*sin(om_c) + cos(ka_c)*cos(om_c))) - z_1*((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*sin(fi_c) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*sin(om_c)*cos(fi_c));
j.coeffRef(2,6) = sin(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_1);
j.coeffRef(2,7) = -sin(fi_1)*sin(ka_1)*cos(om_1) - sin(om_1)*cos(ka_1);
j.coeffRef(2,8) = -cos(fi_1)*cos(om_1);
j.coeffRef(2,9) = -x_1*((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_c)*cos(ka_c)*cos(om_c) - sin(ka_c)*sin(om_c)) + (sin(fi_c)*sin(om_c)*cos(ka_c) + sin(ka_c)*cos(om_c))*cos(fi_1)*cos(om_1)) - y_1*((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(-sin(fi_c)*sin(ka_c)*cos(om_c) - sin(om_c)*cos(ka_c)) + (-sin(fi_c)*sin(ka_c)*sin(om_c) + cos(ka_c)*cos(om_c))*cos(fi_1)*cos(om_1)) - z_1*((-sin(fi_1)*sin(ka_1)*cos(om_1) - sin(om_1)*cos(ka_1))*cos(fi_c)*cos(om_c) - sin(om_c)*cos(fi_1)*cos(fi_c)*cos(om_1));
j.coeffRef(2,10) = -x_1*((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*sin(om_c)*cos(fi_c)*cos(ka_c) - (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*sin(fi_c)*cos(ka_c) - cos(fi_1)*cos(fi_c)*cos(ka_c)*cos(om_1)*cos(om_c)) - y_1*(-(sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*sin(ka_c)*sin(om_c)*cos(fi_c) - (sin(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_1))*sin(fi_c)*sin(ka_c) + sin(ka_c)*cos(fi_1)*cos(fi_c)*cos(om_1)*cos(om_c)) - z_1*(-(-sin(fi_1)*sin(ka_1)*cos(om_1) - sin(om_1)*cos(ka_1))*sin(fi_c)*sin(om_c) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*cos(fi_c) - sin(fi_c)*cos(fi_1)*cos(om_1)*cos(om_c));
j.coeffRef(2,11) = -x_1*((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(-sin(fi_c)*sin(ka_c)*sin(om_c) + cos(ka_c)*cos(om_c)) - (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*sin(ka_c)*cos(fi_c) + (sin(fi_c)*sin(ka_c)*cos(om_c) + sin(om_c)*cos(ka_c))*cos(fi_1)*cos(om_1)) - y_1*((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(-sin(fi_c)*sin(om_c)*cos(ka_c) - sin(ka_c)*cos(om_c)) + (sin(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_1))*cos(fi_c)*cos(ka_c) + (sin(fi_c)*cos(ka_c)*cos(om_c) - sin(ka_c)*sin(om_c))*cos(fi_1)*cos(om_1));
}