inline void point_to_projection_onto_plane_tait_bryan_cw(Eigen::Matrix<double, 3, 1> &delta, double tx_cw, double ty_cw, double tz_cw, double om_cw, double fi_cw, double ka_cw, double x_src_l, double y_src_l, double z_src_l, double x_trg_g, double y_trg_g, double z_trg_g, double a, double b, double c)
{delta.coeffRef(0,0) = -a*(-a*x_trg_g + a*(-tx_cw*cos(fi_cw)*cos(ka_cw) + ty_cw*(-sin(fi_cw)*sin(om_cw)*cos(ka_cw) - sin(ka_cw)*cos(om_cw)) + tz_cw*(sin(fi_cw)*cos(ka_cw)*cos(om_cw) - sin(ka_cw)*sin(om_cw)) + x_src_l*cos(fi_cw)*cos(ka_cw) + y_src_l*(sin(fi_cw)*sin(om_cw)*cos(ka_cw) + sin(ka_cw)*cos(om_cw)) + z_src_l*(-sin(fi_cw)*cos(ka_cw)*cos(om_cw) + sin(ka_cw)*sin(om_cw))) - b*y_trg_g + b*(tx_cw*sin(ka_cw)*cos(fi_cw) + ty_cw*(sin(fi_cw)*sin(ka_cw)*sin(om_cw) - cos(ka_cw)*cos(om_cw)) + tz_cw*(-sin(fi_cw)*sin(ka_cw)*cos(om_cw) - sin(om_cw)*cos(ka_cw)) - x_src_l*sin(ka_cw)*cos(fi_cw) + y_src_l*(-sin(fi_cw)*sin(ka_cw)*sin(om_cw) + cos(ka_cw)*cos(om_cw)) + z_src_l*(sin(fi_cw)*sin(ka_cw)*cos(om_cw) + sin(om_cw)*cos(ka_cw))) - c*z_trg_g + c*(-tx_cw*sin(fi_cw) + ty_cw*sin(om_cw)*cos(fi_cw) - tz_cw*cos(fi_cw)*cos(om_cw) + x_src_l*sin(fi_cw) - y_src_l*sin(om_cw)*cos(fi_cw) + z_src_l*cos(fi_cw)*cos(om_cw)));
delta.coeffRef(1,0) = -b*(-a*x_trg_g + a*(-tx_cw*cos(fi_cw)*cos(ka_cw) + ty_cw*(-sin(fi_cw)*sin(om_cw)*cos(ka_cw) - sin(ka_cw)*cos(om_cw)) + tz_cw*(sin(fi_cw)*cos(ka_cw)*cos(om_cw) - sin(ka_cw)*sin(om_cw)) + x_src_l*cos(fi_cw)*cos(ka_cw) + y_src_l*(sin(fi_cw)*sin(om_cw)*cos(ka_cw) + sin(ka_cw)*cos(om_cw)) + z_src_l*(-sin(fi_cw)*cos(ka_cw)*cos(om_cw) + sin(ka_cw)*sin(om_cw))) - b*y_trg_g + b*(tx_cw*sin(ka_cw)*cos(fi_cw) + ty_cw*(sin(fi_cw)*sin(ka_cw)*sin(om_cw) - cos(ka_cw)*cos(om_cw)) + tz_cw*(-sin(fi_cw)*sin(ka_cw)*cos(om_cw) - sin(om_cw)*cos(ka_cw)) - x_src_l*sin(ka_cw)*cos(fi_cw) + y_src_l*(-sin(fi_cw)*sin(ka_cw)*sin(om_cw) + cos(ka_cw)*cos(om_cw)) + z_src_l*(sin(fi_cw)*sin(ka_cw)*cos(om_cw) + sin(om_cw)*cos(ka_cw))) - c*z_trg_g + c*(-tx_cw*sin(fi_cw) + ty_cw*sin(om_cw)*cos(fi_cw) - tz_cw*cos(fi_cw)*cos(om_cw) + x_src_l*sin(fi_cw) - y_src_l*sin(om_cw)*cos(fi_cw) + z_src_l*cos(fi_cw)*cos(om_cw)));
delta.coeffRef(2,0) = -c*(-a*x_trg_g + a*(-tx_cw*cos(fi_cw)*cos(ka_cw) + ty_cw*(-sin(fi_cw)*sin(om_cw)*cos(ka_cw) - sin(ka_cw)*cos(om_cw)) + tz_cw*(sin(fi_cw)*cos(ka_cw)*cos(om_cw) - sin(ka_cw)*sin(om_cw)) + x_src_l*cos(fi_cw)*cos(ka_cw) + y_src_l*(sin(fi_cw)*sin(om_cw)*cos(ka_cw) + sin(ka_cw)*cos(om_cw)) + z_src_l*(-sin(fi_cw)*cos(ka_cw)*cos(om_cw) + sin(ka_cw)*sin(om_cw))) - b*y_trg_g + b*(tx_cw*sin(ka_cw)*cos(fi_cw) + ty_cw*(sin(fi_cw)*sin(ka_cw)*sin(om_cw) - cos(ka_cw)*cos(om_cw)) + tz_cw*(-sin(fi_cw)*sin(ka_cw)*cos(om_cw) - sin(om_cw)*cos(ka_cw)) - x_src_l*sin(ka_cw)*cos(fi_cw) + y_src_l*(-sin(fi_cw)*sin(ka_cw)*sin(om_cw) + cos(ka_cw)*cos(om_cw)) + z_src_l*(sin(fi_cw)*sin(ka_cw)*cos(om_cw) + sin(om_cw)*cos(ka_cw))) - c*z_trg_g + c*(-tx_cw*sin(fi_cw) + ty_cw*sin(om_cw)*cos(fi_cw) - tz_cw*cos(fi_cw)*cos(om_cw) + x_src_l*sin(fi_cw) - y_src_l*sin(om_cw)*cos(fi_cw) + z_src_l*cos(fi_cw)*cos(om_cw)));
}
inline void point_to_projection_onto_plane_tait_bryan_cw_jacobian(Eigen::Matrix<double, 3, 6> &j, double tx_cw, double ty_cw, double tz_cw, double om_cw, double fi_cw, double ka_cw, double x_src_l, double y_src_l, double z_src_l, double x_trg_g, double y_trg_g, double z_trg_g, double a, double b, double c)
{j.coeffRef(0,0) = -a*(-a*cos(fi_cw)*cos(ka_cw) + b*sin(ka_cw)*cos(fi_cw) - c*sin(fi_cw));
j.coeffRef(0,1) = -a*(a*(-sin(fi_cw)*sin(om_cw)*cos(ka_cw) - sin(ka_cw)*cos(om_cw)) + b*(sin(fi_cw)*sin(ka_cw)*sin(om_cw) - cos(ka_cw)*cos(om_cw)) + c*sin(om_cw)*cos(fi_cw));
j.coeffRef(0,2) = -a*(a*(sin(fi_cw)*cos(ka_cw)*cos(om_cw) - sin(ka_cw)*sin(om_cw)) + b*(-sin(fi_cw)*sin(ka_cw)*cos(om_cw) - sin(om_cw)*cos(ka_cw)) - c*cos(fi_cw)*cos(om_cw));
j.coeffRef(0,3) = -a*(a*(ty_cw*(-sin(fi_cw)*cos(ka_cw)*cos(om_cw) + sin(ka_cw)*sin(om_cw)) + tz_cw*(-sin(fi_cw)*sin(om_cw)*cos(ka_cw) - sin(ka_cw)*cos(om_cw)) + y_src_l*(sin(fi_cw)*cos(ka_cw)*cos(om_cw) - sin(ka_cw)*sin(om_cw)) + z_src_l*(sin(fi_cw)*sin(om_cw)*cos(ka_cw) + sin(ka_cw)*cos(om_cw))) + b*(ty_cw*(sin(fi_cw)*sin(ka_cw)*cos(om_cw) + sin(om_cw)*cos(ka_cw)) + tz_cw*(sin(fi_cw)*sin(ka_cw)*sin(om_cw) - cos(ka_cw)*cos(om_cw)) + y_src_l*(-sin(fi_cw)*sin(ka_cw)*cos(om_cw) - sin(om_cw)*cos(ka_cw)) + z_src_l*(-sin(fi_cw)*sin(ka_cw)*sin(om_cw) + cos(ka_cw)*cos(om_cw))) + c*(ty_cw*cos(fi_cw)*cos(om_cw) + tz_cw*sin(om_cw)*cos(fi_cw) - y_src_l*cos(fi_cw)*cos(om_cw) - z_src_l*sin(om_cw)*cos(fi_cw)));
j.coeffRef(0,4) = -a*(a*(tx_cw*sin(fi_cw)*cos(ka_cw) - ty_cw*sin(om_cw)*cos(fi_cw)*cos(ka_cw) + tz_cw*cos(fi_cw)*cos(ka_cw)*cos(om_cw) - x_src_l*sin(fi_cw)*cos(ka_cw) + y_src_l*sin(om_cw)*cos(fi_cw)*cos(ka_cw) - z_src_l*cos(fi_cw)*cos(ka_cw)*cos(om_cw)) + b*(-tx_cw*sin(fi_cw)*sin(ka_cw) + ty_cw*sin(ka_cw)*sin(om_cw)*cos(fi_cw) - tz_cw*sin(ka_cw)*cos(fi_cw)*cos(om_cw) + x_src_l*sin(fi_cw)*sin(ka_cw) - y_src_l*sin(ka_cw)*sin(om_cw)*cos(fi_cw) + z_src_l*sin(ka_cw)*cos(fi_cw)*cos(om_cw)) + c*(-tx_cw*cos(fi_cw) - ty_cw*sin(fi_cw)*sin(om_cw) + tz_cw*sin(fi_cw)*cos(om_cw) + x_src_l*cos(fi_cw) + y_src_l*sin(fi_cw)*sin(om_cw) - z_src_l*sin(fi_cw)*cos(om_cw)));
j.coeffRef(0,5) = -a*(a*(tx_cw*sin(ka_cw)*cos(fi_cw) + ty_cw*(sin(fi_cw)*sin(ka_cw)*sin(om_cw) - cos(ka_cw)*cos(om_cw)) + tz_cw*(-sin(fi_cw)*sin(ka_cw)*cos(om_cw) - sin(om_cw)*cos(ka_cw)) - x_src_l*sin(ka_cw)*cos(fi_cw) + y_src_l*(-sin(fi_cw)*sin(ka_cw)*sin(om_cw) + cos(ka_cw)*cos(om_cw)) + z_src_l*(sin(fi_cw)*sin(ka_cw)*cos(om_cw) + sin(om_cw)*cos(ka_cw))) + b*(tx_cw*cos(fi_cw)*cos(ka_cw) + ty_cw*(sin(fi_cw)*sin(om_cw)*cos(ka_cw) + sin(ka_cw)*cos(om_cw)) + tz_cw*(-sin(fi_cw)*cos(ka_cw)*cos(om_cw) + sin(ka_cw)*sin(om_cw)) - x_src_l*cos(fi_cw)*cos(ka_cw) + y_src_l*(-sin(fi_cw)*sin(om_cw)*cos(ka_cw) - sin(ka_cw)*cos(om_cw)) + z_src_l*(sin(fi_cw)*cos(ka_cw)*cos(om_cw) - sin(ka_cw)*sin(om_cw))));
j.coeffRef(1,0) = -b*(-a*cos(fi_cw)*cos(ka_cw) + b*sin(ka_cw)*cos(fi_cw) - c*sin(fi_cw));
j.coeffRef(1,1) = -b*(a*(-sin(fi_cw)*sin(om_cw)*cos(ka_cw) - sin(ka_cw)*cos(om_cw)) + b*(sin(fi_cw)*sin(ka_cw)*sin(om_cw) - cos(ka_cw)*cos(om_cw)) + c*sin(om_cw)*cos(fi_cw));
j.coeffRef(1,2) = -b*(a*(sin(fi_cw)*cos(ka_cw)*cos(om_cw) - sin(ka_cw)*sin(om_cw)) + b*(-sin(fi_cw)*sin(ka_cw)*cos(om_cw) - sin(om_cw)*cos(ka_cw)) - c*cos(fi_cw)*cos(om_cw));
j.coeffRef(1,3) = -b*(a*(ty_cw*(-sin(fi_cw)*cos(ka_cw)*cos(om_cw) + sin(ka_cw)*sin(om_cw)) + tz_cw*(-sin(fi_cw)*sin(om_cw)*cos(ka_cw) - sin(ka_cw)*cos(om_cw)) + y_src_l*(sin(fi_cw)*cos(ka_cw)*cos(om_cw) - sin(ka_cw)*sin(om_cw)) + z_src_l*(sin(fi_cw)*sin(om_cw)*cos(ka_cw) + sin(ka_cw)*cos(om_cw))) + b*(ty_cw*(sin(fi_cw)*sin(ka_cw)*cos(om_cw) + sin(om_cw)*cos(ka_cw)) + tz_cw*(sin(fi_cw)*sin(ka_cw)*sin(om_cw) - cos(ka_cw)*cos(om_cw)) + y_src_l*(-sin(fi_cw)*sin(ka_cw)*cos(om_cw) - sin(om_cw)*cos(ka_cw)) + z_src_l*(-sin(fi_cw)*sin(ka_cw)*sin(om_cw) + cos(ka_cw)*cos(om_cw))) + c*(ty_cw*cos(fi_cw)*cos(om_cw) + tz_cw*sin(om_cw)*cos(fi_cw) - y_src_l*cos(fi_cw)*cos(om_cw) - z_src_l*sin(om_cw)*cos(fi_cw)));
j.coeffRef(1,4) = -b*(a*(tx_cw*sin(fi_cw)*cos(ka_cw) - ty_cw*sin(om_cw)*cos(fi_cw)*cos(ka_cw) + tz_cw*cos(fi_cw)*cos(ka_cw)*cos(om_cw) - x_src_l*sin(fi_cw)*cos(ka_cw) + y_src_l*sin(om_cw)*cos(fi_cw)*cos(ka_cw) - z_src_l*cos(fi_cw)*cos(ka_cw)*cos(om_cw)) + b*(-tx_cw*sin(fi_cw)*sin(ka_cw) + ty_cw*sin(ka_cw)*sin(om_cw)*cos(fi_cw) - tz_cw*sin(ka_cw)*cos(fi_cw)*cos(om_cw) + x_src_l*sin(fi_cw)*sin(ka_cw) - y_src_l*sin(ka_cw)*sin(om_cw)*cos(fi_cw) + z_src_l*sin(ka_cw)*cos(fi_cw)*cos(om_cw)) + c*(-tx_cw*cos(fi_cw) - ty_cw*sin(fi_cw)*sin(om_cw) + tz_cw*sin(fi_cw)*cos(om_cw) + x_src_l*cos(fi_cw) + y_src_l*sin(fi_cw)*sin(om_cw) - z_src_l*sin(fi_cw)*cos(om_cw)));
j.coeffRef(1,5) = -b*(a*(tx_cw*sin(ka_cw)*cos(fi_cw) + ty_cw*(sin(fi_cw)*sin(ka_cw)*sin(om_cw) - cos(ka_cw)*cos(om_cw)) + tz_cw*(-sin(fi_cw)*sin(ka_cw)*cos(om_cw) - sin(om_cw)*cos(ka_cw)) - x_src_l*sin(ka_cw)*cos(fi_cw) + y_src_l*(-sin(fi_cw)*sin(ka_cw)*sin(om_cw) + cos(ka_cw)*cos(om_cw)) + z_src_l*(sin(fi_cw)*sin(ka_cw)*cos(om_cw) + sin(om_cw)*cos(ka_cw))) + b*(tx_cw*cos(fi_cw)*cos(ka_cw) + ty_cw*(sin(fi_cw)*sin(om_cw)*cos(ka_cw) + sin(ka_cw)*cos(om_cw)) + tz_cw*(-sin(fi_cw)*cos(ka_cw)*cos(om_cw) + sin(ka_cw)*sin(om_cw)) - x_src_l*cos(fi_cw)*cos(ka_cw) + y_src_l*(-sin(fi_cw)*sin(om_cw)*cos(ka_cw) - sin(ka_cw)*cos(om_cw)) + z_src_l*(sin(fi_cw)*cos(ka_cw)*cos(om_cw) - sin(ka_cw)*sin(om_cw))));
j.coeffRef(2,0) = -c*(-a*cos(fi_cw)*cos(ka_cw) + b*sin(ka_cw)*cos(fi_cw) - c*sin(fi_cw));
j.coeffRef(2,1) = -c*(a*(-sin(fi_cw)*sin(om_cw)*cos(ka_cw) - sin(ka_cw)*cos(om_cw)) + b*(sin(fi_cw)*sin(ka_cw)*sin(om_cw) - cos(ka_cw)*cos(om_cw)) + c*sin(om_cw)*cos(fi_cw));
j.coeffRef(2,2) = -c*(a*(sin(fi_cw)*cos(ka_cw)*cos(om_cw) - sin(ka_cw)*sin(om_cw)) + b*(-sin(fi_cw)*sin(ka_cw)*cos(om_cw) - sin(om_cw)*cos(ka_cw)) - c*cos(fi_cw)*cos(om_cw));
j.coeffRef(2,3) = -c*(a*(ty_cw*(-sin(fi_cw)*cos(ka_cw)*cos(om_cw) + sin(ka_cw)*sin(om_cw)) + tz_cw*(-sin(fi_cw)*sin(om_cw)*cos(ka_cw) - sin(ka_cw)*cos(om_cw)) + y_src_l*(sin(fi_cw)*cos(ka_cw)*cos(om_cw) - sin(ka_cw)*sin(om_cw)) + z_src_l*(sin(fi_cw)*sin(om_cw)*cos(ka_cw) + sin(ka_cw)*cos(om_cw))) + b*(ty_cw*(sin(fi_cw)*sin(ka_cw)*cos(om_cw) + sin(om_cw)*cos(ka_cw)) + tz_cw*(sin(fi_cw)*sin(ka_cw)*sin(om_cw) - cos(ka_cw)*cos(om_cw)) + y_src_l*(-sin(fi_cw)*sin(ka_cw)*cos(om_cw) - sin(om_cw)*cos(ka_cw)) + z_src_l*(-sin(fi_cw)*sin(ka_cw)*sin(om_cw) + cos(ka_cw)*cos(om_cw))) + c*(ty_cw*cos(fi_cw)*cos(om_cw) + tz_cw*sin(om_cw)*cos(fi_cw) - y_src_l*cos(fi_cw)*cos(om_cw) - z_src_l*sin(om_cw)*cos(fi_cw)));
j.coeffRef(2,4) = -c*(a*(tx_cw*sin(fi_cw)*cos(ka_cw) - ty_cw*sin(om_cw)*cos(fi_cw)*cos(ka_cw) + tz_cw*cos(fi_cw)*cos(ka_cw)*cos(om_cw) - x_src_l*sin(fi_cw)*cos(ka_cw) + y_src_l*sin(om_cw)*cos(fi_cw)*cos(ka_cw) - z_src_l*cos(fi_cw)*cos(ka_cw)*cos(om_cw)) + b*(-tx_cw*sin(fi_cw)*sin(ka_cw) + ty_cw*sin(ka_cw)*sin(om_cw)*cos(fi_cw) - tz_cw*sin(ka_cw)*cos(fi_cw)*cos(om_cw) + x_src_l*sin(fi_cw)*sin(ka_cw) - y_src_l*sin(ka_cw)*sin(om_cw)*cos(fi_cw) + z_src_l*sin(ka_cw)*cos(fi_cw)*cos(om_cw)) + c*(-tx_cw*cos(fi_cw) - ty_cw*sin(fi_cw)*sin(om_cw) + tz_cw*sin(fi_cw)*cos(om_cw) + x_src_l*cos(fi_cw) + y_src_l*sin(fi_cw)*sin(om_cw) - z_src_l*sin(fi_cw)*cos(om_cw)));
j.coeffRef(2,5) = -c*(a*(tx_cw*sin(ka_cw)*cos(fi_cw) + ty_cw*(sin(fi_cw)*sin(ka_cw)*sin(om_cw) - cos(ka_cw)*cos(om_cw)) + tz_cw*(-sin(fi_cw)*sin(ka_cw)*cos(om_cw) - sin(om_cw)*cos(ka_cw)) - x_src_l*sin(ka_cw)*cos(fi_cw) + y_src_l*(-sin(fi_cw)*sin(ka_cw)*sin(om_cw) + cos(ka_cw)*cos(om_cw)) + z_src_l*(sin(fi_cw)*sin(ka_cw)*cos(om_cw) + sin(om_cw)*cos(ka_cw))) + b*(tx_cw*cos(fi_cw)*cos(ka_cw) + ty_cw*(sin(fi_cw)*sin(om_cw)*cos(ka_cw) + sin(ka_cw)*cos(om_cw)) + tz_cw*(-sin(fi_cw)*cos(ka_cw)*cos(om_cw) + sin(ka_cw)*sin(om_cw)) - x_src_l*cos(fi_cw)*cos(ka_cw) + y_src_l*(-sin(fi_cw)*sin(om_cw)*cos(ka_cw) - sin(ka_cw)*cos(om_cw)) + z_src_l*(sin(fi_cw)*cos(ka_cw)*cos(om_cw) - sin(ka_cw)*sin(om_cw))));
}