#ifndef _relative_pose_tait_bryan_cw_jacobian_h_
#define _relative_pose_tait_bryan_cw_jacobian_h_
inline void relative_pose_obs_eq_tait_bryan_cw_case1(Eigen::Matrix<double, 6, 1> &delta, double tx_1, double ty_1, double tz_1, double om_1, double fi_1, double ka_1, double tx_2, double ty_2, double tz_2, double om_2, double fi_2, double ka_2, double tx_m, double ty_m, double tz_m, double om_m, double fi_m, double ka_m)
{delta.coeffRef(0,0) = -tx_1 + tx_m - (-tx_2*sin(fi_2) + ty_2*sin(om_2)*cos(fi_2) - tz_2*cos(fi_2)*cos(om_2))*sin(fi_1) + (tx_2*sin(ka_2)*cos(fi_2) + ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2)))*sin(ka_1)*cos(fi_1) - (-tx_2*cos(fi_2)*cos(ka_2) + ty_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)) + tz_2*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2)))*cos(fi_1)*cos(ka_1);
delta.coeffRef(1,0) = -ty_1 + ty_m - (-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(tx_2*sin(ka_2)*cos(fi_2) + ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2))) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-tx_2*cos(fi_2)*cos(ka_2) + ty_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)) + tz_2*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2))) + (-tx_2*sin(fi_2) + ty_2*sin(om_2)*cos(fi_2) - tz_2*cos(fi_2)*cos(om_2))*sin(om_1)*cos(fi_1);
delta.coeffRef(2,0) = -tz_1 + tz_m - (sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(tx_2*sin(ka_2)*cos(fi_2) + ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2))) - (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-tx_2*cos(fi_2)*cos(ka_2) + ty_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)) + tz_2*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2))) - (-tx_2*sin(fi_2) + ty_2*sin(om_2)*cos(fi_2) - tz_2*cos(fi_2)*cos(om_2))*cos(fi_1)*cos(om_1);
delta.coeffRef(3,0) = om_m - atan2(-(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2), (sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2));
delta.coeffRef(4,0) = fi_m - asin(-(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2))*sin(ka_1)*cos(fi_1) + (-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*cos(fi_2)*cos(om_2));
delta.coeffRef(5,0) = ka_m - atan2((-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) - (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*sin(om_2)*cos(fi_2), sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2));
}
inline void relative_pose_obs_eq_tait_bryan_cw_case1_jacobian(Eigen::Matrix<double, 6, 12, Eigen::RowMajor> &j, double tx_1, double ty_1, double tz_1, double om_1, double fi_1, double ka_1, double tx_2, double ty_2, double tz_2, double om_2, double fi_2, double ka_2)
{j.coeffRef(0,0) = -1;
j.coeffRef(0,1) = 0;
j.coeffRef(0,2) = 0;
j.coeffRef(0,3) = 0;
j.coeffRef(0,4) = (tx_2*sin(fi_2) - ty_2*sin(om_2)*cos(fi_2) + tz_2*cos(fi_2)*cos(om_2))*cos(fi_1) - (tx_2*sin(ka_2)*cos(fi_2) + ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2)))*sin(fi_1)*sin(ka_1) - (tx_2*cos(fi_2)*cos(ka_2) - ty_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)) - tz_2*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2)))*sin(fi_1)*cos(ka_1);
j.coeffRef(0,5) = (tx_2*sin(ka_2)*cos(fi_2) + ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2)))*cos(fi_1)*cos(ka_1) - (tx_2*cos(fi_2)*cos(ka_2) - ty_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)) - tz_2*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2)))*sin(ka_1)*cos(fi_1);
j.coeffRef(0,6) = sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2);
j.coeffRef(0,7) = (sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) + (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) - sin(fi_1)*sin(om_2)*cos(fi_2);
j.coeffRef(0,8) = (-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2))*sin(ka_1)*cos(fi_1) + (-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*cos(fi_2)*cos(om_2);
j.coeffRef(0,9) = (ty_2*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + tz_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)))*sin(ka_1)*cos(fi_1) + (-ty_2*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) - tz_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)))*cos(fi_1)*cos(ka_1) + (-ty_2*cos(fi_2)*cos(om_2) - tz_2*sin(om_2)*cos(fi_2))*sin(fi_1);
j.coeffRef(0,10) = (tx_2*cos(fi_2) + ty_2*sin(fi_2)*sin(om_2) - tz_2*sin(fi_2)*cos(om_2))*sin(fi_1) + (-tx_2*sin(fi_2)*sin(ka_2) + ty_2*sin(ka_2)*sin(om_2)*cos(fi_2) - tz_2*sin(ka_2)*cos(fi_2)*cos(om_2))*sin(ka_1)*cos(fi_1) + (-tx_2*sin(fi_2)*cos(ka_2) + ty_2*sin(om_2)*cos(fi_2)*cos(ka_2) - tz_2*cos(fi_2)*cos(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1);
j.coeffRef(0,11) = (-tx_2*sin(ka_2)*cos(fi_2) - ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) - tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2)))*cos(fi_1)*cos(ka_1) + (tx_2*cos(fi_2)*cos(ka_2) + ty_2*(sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)))*sin(ka_1)*cos(fi_1);
j.coeffRef(1,0) = 0;
j.coeffRef(1,1) = -1;
j.coeffRef(1,2) = 0;
j.coeffRef(1,3) = (sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(tx_2*sin(ka_2)*cos(fi_2) + ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2))) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-tx_2*cos(fi_2)*cos(ka_2) + ty_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)) + tz_2*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2))) + (-tx_2*sin(fi_2) + ty_2*sin(om_2)*cos(fi_2) - tz_2*cos(fi_2)*cos(om_2))*cos(fi_1)*cos(om_1);
j.coeffRef(1,4) = -(-tx_2*sin(fi_2) + ty_2*sin(om_2)*cos(fi_2) - tz_2*cos(fi_2)*cos(om_2))*sin(fi_1)*sin(om_1) + (tx_2*sin(ka_2)*cos(fi_2) + ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2)))*sin(ka_1)*sin(om_1)*cos(fi_1) - (-tx_2*cos(fi_2)*cos(ka_2) + ty_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)) + tz_2*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2)))*sin(om_1)*cos(fi_1)*cos(ka_1);
j.coeffRef(1,5) = (sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1))*(-tx_2*cos(fi_2)*cos(ka_2) + ty_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)) + tz_2*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2))) + (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(tx_2*sin(ka_2)*cos(fi_2) + ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2)));
j.coeffRef(1,6) = (sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1))*sin(ka_2)*cos(fi_2) - (-sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1))*cos(fi_2)*cos(ka_2) - sin(fi_2)*sin(om_1)*cos(fi_1);
j.coeffRef(1,7) = (sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + (-sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1))*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)) + sin(om_1)*sin(om_2)*cos(fi_1)*cos(fi_2);
j.coeffRef(1,8) = (sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1))*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2)) + (-sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1))*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2)) - sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2);
j.coeffRef(1,9) = (ty_2*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + tz_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)))*(sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1)) + (ty_2*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + tz_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)))*(-sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1)) + (ty_2*cos(fi_2)*cos(om_2) + tz_2*sin(om_2)*cos(fi_2))*sin(om_1)*cos(fi_1);
j.coeffRef(1,10) = (sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1))*(-tx_2*sin(fi_2)*sin(ka_2) + ty_2*sin(ka_2)*sin(om_2)*cos(fi_2) - tz_2*sin(ka_2)*cos(fi_2)*cos(om_2)) + (-sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1))*(tx_2*sin(fi_2)*cos(ka_2) - ty_2*sin(om_2)*cos(fi_2)*cos(ka_2) + tz_2*cos(fi_2)*cos(ka_2)*cos(om_2)) + (-tx_2*cos(fi_2) - ty_2*sin(fi_2)*sin(om_2) + tz_2*sin(fi_2)*cos(om_2))*sin(om_1)*cos(fi_1);
j.coeffRef(1,11) = (sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1))*(tx_2*cos(fi_2)*cos(ka_2) + ty_2*(sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2))) + (-sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1))*(tx_2*sin(ka_2)*cos(fi_2) + ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2)));
j.coeffRef(2,0) = 0;
j.coeffRef(2,1) = 0;
j.coeffRef(2,2) = -1;
j.coeffRef(2,3) = (sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1))*(tx_2*sin(ka_2)*cos(fi_2) + ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2))) + (-sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1))*(-tx_2*cos(fi_2)*cos(ka_2) + ty_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)) + tz_2*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2))) - (tx_2*sin(fi_2) - ty_2*sin(om_2)*cos(fi_2) + tz_2*cos(fi_2)*cos(om_2))*sin(om_1)*cos(fi_1);
j.coeffRef(2,4) = -(tx_2*sin(fi_2) - ty_2*sin(om_2)*cos(fi_2) + tz_2*cos(fi_2)*cos(om_2))*sin(fi_1)*cos(om_1) - (tx_2*sin(ka_2)*cos(fi_2) + ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2)))*sin(ka_1)*cos(fi_1)*cos(om_1) + (-tx_2*cos(fi_2)*cos(ka_2) + ty_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)) + tz_2*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2)))*cos(fi_1)*cos(ka_1)*cos(om_1);
j.coeffRef(2,5) = (-sin(fi_1)*sin(ka_1)*cos(om_1) - sin(om_1)*cos(ka_1))*(-tx_2*cos(fi_2)*cos(ka_2) + ty_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)) + tz_2*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2))) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(tx_2*sin(ka_2)*cos(fi_2) + ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2)));
j.coeffRef(2,6) = (-sin(fi_1)*sin(ka_1)*cos(om_1) - sin(om_1)*cos(ka_1))*sin(ka_2)*cos(fi_2) - (sin(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_1))*cos(fi_2)*cos(ka_2) + sin(fi_2)*cos(fi_1)*cos(om_1);
j.coeffRef(2,7) = (-sin(fi_1)*sin(ka_1)*cos(om_1) - sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + (sin(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_1))*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)) - sin(om_2)*cos(fi_1)*cos(fi_2)*cos(om_1);
j.coeffRef(2,8) = (-sin(fi_1)*sin(ka_1)*cos(om_1) - sin(om_1)*cos(ka_1))*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2)) + (sin(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_1))*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2);
j.coeffRef(2,9) = (ty_2*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + tz_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)))*(-sin(fi_1)*sin(ka_1)*cos(om_1) - sin(om_1)*cos(ka_1)) + (ty_2*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + tz_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)))*(sin(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_1)) + (-ty_2*cos(fi_2)*cos(om_2) - tz_2*sin(om_2)*cos(fi_2))*cos(fi_1)*cos(om_1);
j.coeffRef(2,10) = (-sin(fi_1)*sin(ka_1)*cos(om_1) - sin(om_1)*cos(ka_1))*(-tx_2*sin(fi_2)*sin(ka_2) + ty_2*sin(ka_2)*sin(om_2)*cos(fi_2) - tz_2*sin(ka_2)*cos(fi_2)*cos(om_2)) + (sin(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_1))*(tx_2*sin(fi_2)*cos(ka_2) - ty_2*sin(om_2)*cos(fi_2)*cos(ka_2) + tz_2*cos(fi_2)*cos(ka_2)*cos(om_2)) + (tx_2*cos(fi_2) + ty_2*sin(fi_2)*sin(om_2) - tz_2*sin(fi_2)*cos(om_2))*cos(fi_1)*cos(om_1);
j.coeffRef(2,11) = (-sin(fi_1)*sin(ka_1)*cos(om_1) - sin(om_1)*cos(ka_1))*(tx_2*cos(fi_2)*cos(ka_2) + ty_2*(sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2))) + (sin(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_1))*(tx_2*sin(ka_2)*cos(fi_2) + ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2)));
j.coeffRef(3,0) = 0;
j.coeffRef(3,1) = 0;
j.coeffRef(3,2) = 0;
j.coeffRef(3,3) = -pow((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) - sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2), 2)/(pow(-(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2), 2) + pow((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2), 2)) - pow((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2), 2)/(pow(-(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2), 2) + pow((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2), 2));
j.coeffRef(3,4) = -((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) - sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2))*((sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2))*sin(ka_1)*cos(fi_1)*cos(om_1) - (-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2))*cos(fi_1)*cos(ka_1)*cos(om_1) - sin(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2))/(pow(-(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2), 2) + pow((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2), 2)) - ((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2))*((sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2))*sin(ka_1)*sin(om_1)*cos(fi_1) - (-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2))*sin(om_1)*cos(fi_1)*cos(ka_1) - sin(fi_1)*sin(om_1)*cos(fi_2)*cos(om_2))/(pow(-(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2), 2) + pow((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2), 2));
j.coeffRef(3,5) = -((sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)))*((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2))/(pow(-(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2), 2) + pow((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2), 2)) - ((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + (sin(fi_1)*cos(ka_1)*cos(om_1) - sin(ka_1)*sin(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)))*((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) - sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2))/(pow(-(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2), 2) + pow((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2), 2));
j.coeffRef(3,6) = 0;
j.coeffRef(3,7) = 0;
j.coeffRef(3,8) = 0;
j.coeffRef(3,9) = -((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) - sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2))*((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2)) - sin(om_2)*cos(fi_1)*cos(fi_2)*cos(om_1))/(pow(-(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2), 2) + pow((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2), 2)) - ((sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1))*(-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2)) + (-sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1))*(sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2)) - sin(om_1)*sin(om_2)*cos(fi_1)*cos(fi_2))*((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2))/(pow(-(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2), 2) + pow((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2), 2));
j.coeffRef(3,10) = -((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) - sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2))*((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*sin(ka_2)*cos(fi_2)*cos(om_2) - (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*cos(fi_2)*cos(ka_2)*cos(om_2) - sin(fi_2)*cos(fi_1)*cos(om_1)*cos(om_2))/(pow(-(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2), 2) + pow((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2), 2)) - ((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2))*((sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1))*sin(ka_2)*cos(fi_2)*cos(om_2) - (-sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1))*cos(fi_2)*cos(ka_2)*cos(om_2) - sin(fi_2)*sin(om_1)*cos(fi_1)*cos(om_2))/(pow(-(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2), 2) + pow((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2), 2));
j.coeffRef(3,11) = -((sin(fi_1)*sin(ka_1)*sin(om_1) - cos(ka_1)*cos(om_1))*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2)) + (-sin(fi_1)*sin(om_1)*cos(ka_1) - sin(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)))*((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2))/(pow(-(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2), 2) + pow((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2), 2)) - ((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)))*((-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) - sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2))/(pow(-(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2), 2) + pow((sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2), 2));
j.coeffRef(4,0) = 0;
j.coeffRef(4,1) = 0;
j.coeffRef(4,2) = 0;
j.coeffRef(4,3) = 0;
j.coeffRef(4,4) = -(-(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2))*sin(fi_1)*sin(ka_1) - (-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2))*sin(fi_1)*cos(ka_1) + cos(fi_1)*cos(fi_2)*cos(om_2))/sqrt(1 - pow(-(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2))*sin(ka_1)*cos(fi_1) + (-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*cos(fi_2)*cos(om_2), 2));
j.coeffRef(4,5) = -((-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2))*cos(fi_1)*cos(ka_1) - (-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2))*sin(ka_1)*cos(fi_1))/sqrt(1 - pow(-(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2))*sin(ka_1)*cos(fi_1) + (-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*cos(fi_2)*cos(om_2), 2));
j.coeffRef(4,6) = 0;
j.coeffRef(4,7) = 0;
j.coeffRef(4,8) = 0;
j.coeffRef(4,9) = -((sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) + (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) - sin(fi_1)*sin(om_2)*cos(fi_2))/sqrt(1 - pow(-(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2))*sin(ka_1)*cos(fi_1) + (-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*cos(fi_2)*cos(om_2), 2));
j.coeffRef(4,10) = -(-sin(fi_1)*sin(fi_2)*cos(om_2) - sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2)*cos(om_2) - cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2)*cos(om_2))/sqrt(1 - pow(-(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2))*sin(ka_1)*cos(fi_1) + (-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*cos(fi_2)*cos(om_2), 2));
j.coeffRef(4,11) = -((sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2))*cos(fi_1)*cos(ka_1) + (-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2))*sin(ka_1)*cos(fi_1))/sqrt(1 - pow(-(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2))*sin(ka_1)*cos(fi_1) + (-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*cos(fi_2)*cos(om_2), 2));
j.coeffRef(5,0) = 0;
j.coeffRef(5,1) = 0;
j.coeffRef(5,2) = 0;
j.coeffRef(5,3) = 0;
j.coeffRef(5,4) = -(sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2))*(-(-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*sin(fi_1)*sin(ka_1) - (-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2))*sin(fi_1)*cos(ka_1) + sin(om_2)*cos(fi_1)*cos(fi_2))/(pow(sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2), 2) + pow((-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) - (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*sin(om_2)*cos(fi_2), 2)) - (-(-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) + (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) - sin(fi_1)*sin(om_2)*cos(fi_2))*(-sin(fi_1)*sin(ka_1)*sin(ka_2)*cos(fi_2) - sin(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2) + sin(fi_2)*cos(fi_1))/(pow(sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2), 2) + pow((-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) - (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*sin(om_2)*cos(fi_2), 2));
j.coeffRef(5,5) = -((-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) - (-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1))*(sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2))/(pow(sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2), 2) + pow((-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) - (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*sin(om_2)*cos(fi_2), 2)) - (-sin(ka_1)*cos(fi_1)*cos(fi_2)*cos(ka_2) + sin(ka_2)*cos(fi_1)*cos(fi_2)*cos(ka_1))*(-(-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) + (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) - sin(fi_1)*sin(om_2)*cos(fi_2))/(pow(sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2), 2) + pow((-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) - (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*sin(om_2)*cos(fi_2), 2));
j.coeffRef(5,6) = 0;
j.coeffRef(5,7) = 0;
j.coeffRef(5,8) = 0;
j.coeffRef(5,9) = -(sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2))*((-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2))*sin(ka_1)*cos(fi_1) + (-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*cos(fi_2)*cos(om_2))/(pow(sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2), 2) + pow((-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) - (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*sin(om_2)*cos(fi_2), 2));
j.coeffRef(5,10) = -(sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2))*(-sin(fi_1)*sin(fi_2)*sin(om_2) - sin(ka_1)*sin(ka_2)*sin(om_2)*cos(fi_1)*cos(fi_2) - sin(om_2)*cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2))/(pow(sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2), 2) + pow((-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) - (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*sin(om_2)*cos(fi_2), 2)) - (sin(fi_1)*cos(fi_2) - sin(fi_2)*sin(ka_1)*sin(ka_2)*cos(fi_1) - sin(fi_2)*cos(fi_1)*cos(ka_1)*cos(ka_2))*(-(-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) + (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) - sin(fi_1)*sin(om_2)*cos(fi_2))/(pow(sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2), 2) + pow((-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) - (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*sin(om_2)*cos(fi_2), 2));
j.coeffRef(5,11) = -((sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) + (-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1))*(sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2))/(pow(sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2), 2) + pow((-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) - (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*sin(om_2)*cos(fi_2), 2)) - (sin(ka_1)*cos(fi_1)*cos(fi_2)*cos(ka_2) - sin(ka_2)*cos(fi_1)*cos(fi_2)*cos(ka_1))*(-(-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) + (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) - sin(fi_1)*sin(om_2)*cos(fi_2))/(pow(sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2), 2) + pow((-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) - (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*sin(om_2)*cos(fi_2), 2));
}inline void relative_pose_tait_bryan_cw_case1(Eigen::Matrix<double, 6, 1> &relative_pose, double tx_1, double ty_1, double tz_1, double om_1, double fi_1, double ka_1, double tx_2, double ty_2, double tz_2, double om_2, double fi_2, double ka_2)
{relative_pose.coeffRef(0,0) = tx_1 + (-tx_2*sin(fi_2) + ty_2*sin(om_2)*cos(fi_2) - tz_2*cos(fi_2)*cos(om_2))*sin(fi_1) - (tx_2*sin(ka_2)*cos(fi_2) + ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2)))*sin(ka_1)*cos(fi_1) + (-tx_2*cos(fi_2)*cos(ka_2) + ty_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)) + tz_2*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2)))*cos(fi_1)*cos(ka_1);
relative_pose.coeffRef(1,0) = ty_1 + (-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(tx_2*sin(ka_2)*cos(fi_2) + ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2))) + (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-tx_2*cos(fi_2)*cos(ka_2) + ty_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)) + tz_2*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2))) - (-tx_2*sin(fi_2) + ty_2*sin(om_2)*cos(fi_2) - tz_2*cos(fi_2)*cos(om_2))*sin(om_1)*cos(fi_1);
relative_pose.coeffRef(2,0) = tz_1 + (sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(tx_2*sin(ka_2)*cos(fi_2) + ty_2*(sin(fi_2)*sin(ka_2)*sin(om_2) - cos(ka_2)*cos(om_2)) + tz_2*(-sin(fi_2)*sin(ka_2)*cos(om_2) - sin(om_2)*cos(ka_2))) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-tx_2*cos(fi_2)*cos(ka_2) + ty_2*(-sin(fi_2)*sin(om_2)*cos(ka_2) - sin(ka_2)*cos(om_2)) + tz_2*(sin(fi_2)*cos(ka_2)*cos(om_2) - sin(ka_2)*sin(om_2))) + (-tx_2*sin(fi_2) + ty_2*sin(om_2)*cos(fi_2) - tz_2*cos(fi_2)*cos(om_2))*cos(fi_1)*cos(om_1);
relative_pose.coeffRef(3,0) = atan2(-(-sin(fi_1)*sin(ka_1)*sin(om_1) + cos(ka_1)*cos(om_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) - (sin(fi_1)*sin(om_1)*cos(ka_1) + sin(ka_1)*cos(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + sin(om_1)*cos(fi_1)*cos(fi_2)*cos(om_2), (sin(fi_1)*sin(ka_1)*cos(om_1) + sin(om_1)*cos(ka_1))*(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2)) + (-sin(fi_1)*cos(ka_1)*cos(om_1) + sin(ka_1)*sin(om_1))*(-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2)) + cos(fi_1)*cos(fi_2)*cos(om_1)*cos(om_2));
relative_pose.coeffRef(4,0) = asin(-(sin(fi_2)*sin(ka_2)*cos(om_2) + sin(om_2)*cos(ka_2))*sin(ka_1)*cos(fi_1) + (-sin(fi_2)*cos(ka_2)*cos(om_2) + sin(ka_2)*sin(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*cos(fi_2)*cos(om_2));
relative_pose.coeffRef(5,0) = atan2((-sin(fi_2)*sin(ka_2)*sin(om_2) + cos(ka_2)*cos(om_2))*sin(ka_1)*cos(fi_1) - (sin(fi_2)*sin(om_2)*cos(ka_2) + sin(ka_2)*cos(om_2))*cos(fi_1)*cos(ka_1) + sin(fi_1)*sin(om_2)*cos(fi_2), sin(fi_1)*sin(fi_2) + sin(ka_1)*sin(ka_2)*cos(fi_1)*cos(fi_2) + cos(fi_1)*cos(fi_2)*cos(ka_1)*cos(ka_2));
}

#endif