inline void metric_camera_colinearity_tait_bryan_wc(double &ksi, double &eta, double ksi_0, double eta_0, double c, double tx, double ty, double tz, double om, double fi, double ka, double px, double py, double pz)
{ksi = -c*((px - tx)*cos(fi)*cos(ka) + (py - ty)*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + (pz - tz)*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) + ksi_0;
eta = -c*(-(px - tx)*sin(ka)*cos(fi) + (py - ty)*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + (pz - tz)*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) + eta_0;
}
inline void observation_equation_metric_camera_colinearity_tait_bryan_wc(Eigen::Matrix<double, 2, 1> &delta, double ksi_0, double eta_0, double c, double tx, double ty, double tz, double om, double fi, double ka, double px, double py, double pz, double ksi_kp, double eta_kp)
{delta.coeffRef(0,0) = c*((px - tx)*cos(fi)*cos(ka) + (py - ty)*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + (pz - tz)*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) - ksi_0 + ksi_kp;
delta.coeffRef(1,0) = c*(-(px - tx)*sin(ka)*cos(fi) + (py - ty)*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + (pz - tz)*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) - eta_0 + eta_kp;
}
inline void observation_equation_metric_camera_colinearity_tait_bryan_wc_jacobian(Eigen::Matrix<double, 2, 9, Eigen::RowMajor> &j, double ksi_0, double eta_0, double c, double tx, double ty, double tz, double om, double fi, double ka, double px, double py, double pz, double ksi_kp, double eta_kp)
{j.coeffRef(0,0) = -c*cos(fi)*cos(ka)/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) + c*((px - tx)*cos(fi)*cos(ka) + (py - ty)*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + (pz - tz)*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)))*sin(fi)/pow((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om), 2);
j.coeffRef(0,1) = c*(-sin(fi)*sin(om)*cos(ka) - sin(ka)*cos(om))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) - c*((px - tx)*cos(fi)*cos(ka) + (py - ty)*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + (pz - tz)*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)))*sin(om)*cos(fi)/pow((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om), 2);
j.coeffRef(0,2) = c*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) + c*((px - tx)*cos(fi)*cos(ka) + (py - ty)*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + (pz - tz)*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)))*cos(fi)*cos(om)/pow((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om), 2);
j.coeffRef(0,3) = c*((py - ty)*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om)) + (pz - tz)*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) + c*(-(-py + ty)*cos(fi)*cos(om) + (pz - tz)*sin(om)*cos(fi))*((px - tx)*cos(fi)*cos(ka) + (py - ty)*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + (pz - tz)*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)))/pow((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om), 2);
j.coeffRef(0,4) = c*(-(px - tx)*sin(fi)*cos(ka) + (py - ty)*sin(om)*cos(fi)*cos(ka) - (pz - tz)*cos(fi)*cos(ka)*cos(om))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) + c*(-(px - tx)*cos(fi) + (-py + ty)*sin(fi)*sin(om) + (pz - tz)*sin(fi)*cos(om))*((px - tx)*cos(fi)*cos(ka) + (py - ty)*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + (pz - tz)*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)))/pow((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om), 2);
j.coeffRef(0,5) = c*(-(px - tx)*sin(ka)*cos(fi) + (py - ty)*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + (pz - tz)*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om));
j.coeffRef(0,6) = c*cos(fi)*cos(ka)/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) - c*((px - tx)*cos(fi)*cos(ka) + (py - ty)*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + (pz - tz)*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)))*sin(fi)/pow((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om), 2);
j.coeffRef(0,7) = c*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) + c*((px - tx)*cos(fi)*cos(ka) + (py - ty)*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + (pz - tz)*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)))*sin(om)*cos(fi)/pow((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om), 2);
j.coeffRef(0,8) = c*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) - c*((px - tx)*cos(fi)*cos(ka) + (py - ty)*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + (pz - tz)*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)))*cos(fi)*cos(om)/pow((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om), 2);
j.coeffRef(1,0) = c*sin(ka)*cos(fi)/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) + c*(-(px - tx)*sin(ka)*cos(fi) + (py - ty)*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + (pz - tz)*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)))*sin(fi)/pow((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om), 2);
j.coeffRef(1,1) = c*(sin(fi)*sin(ka)*sin(om) - cos(ka)*cos(om))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) - c*(-(px - tx)*sin(ka)*cos(fi) + (py - ty)*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + (pz - tz)*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)))*sin(om)*cos(fi)/pow((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om), 2);
j.coeffRef(1,2) = c*(-sin(fi)*sin(ka)*cos(om) - sin(om)*cos(ka))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) + c*(-(px - tx)*sin(ka)*cos(fi) + (py - ty)*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + (pz - tz)*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)))*cos(fi)*cos(om)/pow((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om), 2);
j.coeffRef(1,3) = c*((py - ty)*(-sin(fi)*sin(ka)*cos(om) - sin(om)*cos(ka)) + (pz - tz)*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) + c*(-(-py + ty)*cos(fi)*cos(om) + (pz - tz)*sin(om)*cos(fi))*(-(px - tx)*sin(ka)*cos(fi) + (py - ty)*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + (pz - tz)*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)))/pow((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om), 2);
j.coeffRef(1,4) = c*(-(-px + tx)*sin(fi)*sin(ka) - (py - ty)*sin(ka)*sin(om)*cos(fi) + (pz - tz)*sin(ka)*cos(fi)*cos(om))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) + c*(-(px - tx)*cos(fi) + (-py + ty)*sin(fi)*sin(om) + (pz - tz)*sin(fi)*cos(om))*(-(px - tx)*sin(ka)*cos(fi) + (py - ty)*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + (pz - tz)*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)))/pow((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om), 2);
j.coeffRef(1,5) = c*((-px + tx)*cos(fi)*cos(ka) + (py - ty)*(-sin(fi)*sin(om)*cos(ka) - sin(ka)*cos(om)) + (pz - tz)*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om)))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om));
j.coeffRef(1,6) = -c*sin(ka)*cos(fi)/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) - c*(-(px - tx)*sin(ka)*cos(fi) + (py - ty)*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + (pz - tz)*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)))*sin(fi)/pow((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om), 2);
j.coeffRef(1,7) = c*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) + c*(-(px - tx)*sin(ka)*cos(fi) + (py - ty)*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + (pz - tz)*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)))*sin(om)*cos(fi)/pow((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om), 2);
j.coeffRef(1,8) = c*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka))/((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om)) - c*(-(px - tx)*sin(ka)*cos(fi) + (py - ty)*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + (pz - tz)*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)))*cos(fi)*cos(om)/pow((px - tx)*sin(fi) - (py - ty)*sin(om)*cos(fi) + (pz - tz)*cos(fi)*cos(om), 2);
}