inline void observation_equation_perspective_camera_with_K_tait_bryan_wc(Eigen::Matrix<double, 2, 1> &delta, double fx, double fy, double cx, double cy, double tx, double ty, double tz, double om, double fi, double ka, double px, double py, double pz, double u_kp, double v_kp)
{delta.coeffRef(0,0) = -cx - 1.0*fx*(px*cos(fi)*cos(ka) + py*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + pz*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)) - tx*cos(fi)*cos(ka) + ty*(-sin(fi)*sin(om)*cos(ka) - sin(ka)*cos(om)) + tz*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om)))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) + u_kp;
delta.coeffRef(1,0) = -cy - 1.0*fy*(-px*sin(ka)*cos(fi) + py*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + pz*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)) + tx*sin(ka)*cos(fi) + ty*(sin(fi)*sin(ka)*sin(om) - cos(ka)*cos(om)) + tz*(-sin(fi)*sin(ka)*cos(om) - sin(om)*cos(ka)))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) + v_kp;
}inline void projection_perspective_camera_with_K_tait_bryan_wc(double &u, double &v, double fx, double fy, double cx, double cy, double tx, double ty, double tz, double om, double fi, double ka, double px, double py, double pz)
{u = cx + 1.0*fx*(px*cos(fi)*cos(ka) + py*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + pz*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)) - tx*cos(fi)*cos(ka) + ty*(-sin(fi)*sin(om)*cos(ka) - sin(ka)*cos(om)) + tz*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om)))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om));
v = cy + 1.0*fy*(-px*sin(ka)*cos(fi) + py*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + pz*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)) + tx*sin(ka)*cos(fi) + ty*(sin(fi)*sin(ka)*sin(om) - cos(ka)*cos(om)) + tz*(-sin(fi)*sin(ka)*cos(om) - sin(om)*cos(ka)))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om));
}
inline void observation_equation_perspective_camera_with_K_tait_bryan_wc_jacobian(Eigen::Matrix<double, 2, 13> &j, double fx, double fy, double cx, double cy, double tx, double ty, double tz, double om, double fi, double ka, double px, double py, double pz)
{j.coeffRef(0,0) = -1.0*(px*cos(fi)*cos(ka) + py*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + pz*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)) - tx*cos(fi)*cos(ka) + ty*(-sin(fi)*sin(om)*cos(ka) - sin(ka)*cos(om)) + tz*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om)))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om));
j.coeffRef(0,1) = 0;
j.coeffRef(0,2) = -1;
j.coeffRef(0,3) = 0;
j.coeffRef(0,4) = 1.0*fx*cos(fi)*cos(ka)/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) - 1.0*fx*(px*cos(fi)*cos(ka) + py*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + pz*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)) - tx*cos(fi)*cos(ka) + ty*(-sin(fi)*sin(om)*cos(ka) - sin(ka)*cos(om)) + tz*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om)))*sin(fi)/pow(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om), 2);
j.coeffRef(0,5) = -1.0*fx*(-sin(fi)*sin(om)*cos(ka) - sin(ka)*cos(om))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) + 1.0*fx*(px*cos(fi)*cos(ka) + py*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + pz*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)) - tx*cos(fi)*cos(ka) + ty*(-sin(fi)*sin(om)*cos(ka) - sin(ka)*cos(om)) + tz*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om)))*sin(om)*cos(fi)/pow(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om), 2);
j.coeffRef(0,6) = -1.0*fx*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) - 1.0*fx*(px*cos(fi)*cos(ka) + py*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + pz*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)) - tx*cos(fi)*cos(ka) + ty*(-sin(fi)*sin(om)*cos(ka) - sin(ka)*cos(om)) + tz*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om)))*cos(fi)*cos(om)/pow(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om), 2);
j.coeffRef(0,7) = -1.0*fx*(py*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om)) + pz*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + ty*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)) + tz*(-sin(fi)*sin(om)*cos(ka) - sin(ka)*cos(om)))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) - 1.0*fx*(py*cos(fi)*cos(om) + pz*sin(om)*cos(fi) - ty*cos(fi)*cos(om) - tz*sin(om)*cos(fi))*(px*cos(fi)*cos(ka) + py*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + pz*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)) - tx*cos(fi)*cos(ka) + ty*(-sin(fi)*sin(om)*cos(ka) - sin(ka)*cos(om)) + tz*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om)))/pow(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om), 2);
j.coeffRef(0,8) = -1.0*fx*(-px*sin(fi)*cos(ka) + py*sin(om)*cos(fi)*cos(ka) - pz*cos(fi)*cos(ka)*cos(om) + tx*sin(fi)*cos(ka) - ty*sin(om)*cos(fi)*cos(ka) + tz*cos(fi)*cos(ka)*cos(om))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) - 1.0*fx*(-px*cos(fi) - py*sin(fi)*sin(om) + pz*sin(fi)*cos(om) + tx*cos(fi) + ty*sin(fi)*sin(om) - tz*sin(fi)*cos(om))*(px*cos(fi)*cos(ka) + py*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + pz*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)) - tx*cos(fi)*cos(ka) + ty*(-sin(fi)*sin(om)*cos(ka) - sin(ka)*cos(om)) + tz*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om)))/pow(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om), 2);
j.coeffRef(0,9) = -1.0*fx*(-px*sin(ka)*cos(fi) + py*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + pz*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)) + tx*sin(ka)*cos(fi) + ty*(sin(fi)*sin(ka)*sin(om) - cos(ka)*cos(om)) + tz*(-sin(fi)*sin(ka)*cos(om) - sin(om)*cos(ka)))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om));
j.coeffRef(0,10) = -1.0*fx*cos(fi)*cos(ka)/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) + 1.0*fx*(px*cos(fi)*cos(ka) + py*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + pz*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)) - tx*cos(fi)*cos(ka) + ty*(-sin(fi)*sin(om)*cos(ka) - sin(ka)*cos(om)) + tz*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om)))*sin(fi)/pow(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om), 2);
j.coeffRef(0,11) = -1.0*fx*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) - 1.0*fx*(px*cos(fi)*cos(ka) + py*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + pz*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)) - tx*cos(fi)*cos(ka) + ty*(-sin(fi)*sin(om)*cos(ka) - sin(ka)*cos(om)) + tz*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om)))*sin(om)*cos(fi)/pow(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om), 2);
j.coeffRef(0,12) = -1.0*fx*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) + 1.0*fx*(px*cos(fi)*cos(ka) + py*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + pz*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)) - tx*cos(fi)*cos(ka) + ty*(-sin(fi)*sin(om)*cos(ka) - sin(ka)*cos(om)) + tz*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om)))*cos(fi)*cos(om)/pow(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om), 2);
j.coeffRef(1,0) = 0;
j.coeffRef(1,1) = -1.0*(-px*sin(ka)*cos(fi) + py*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + pz*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)) + tx*sin(ka)*cos(fi) + ty*(sin(fi)*sin(ka)*sin(om) - cos(ka)*cos(om)) + tz*(-sin(fi)*sin(ka)*cos(om) - sin(om)*cos(ka)))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om));
j.coeffRef(1,2) = 0;
j.coeffRef(1,3) = -1;
j.coeffRef(1,4) = -1.0*fy*sin(ka)*cos(fi)/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) - 1.0*fy*(-px*sin(ka)*cos(fi) + py*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + pz*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)) + tx*sin(ka)*cos(fi) + ty*(sin(fi)*sin(ka)*sin(om) - cos(ka)*cos(om)) + tz*(-sin(fi)*sin(ka)*cos(om) - sin(om)*cos(ka)))*sin(fi)/pow(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om), 2);
j.coeffRef(1,5) = -1.0*fy*(sin(fi)*sin(ka)*sin(om) - cos(ka)*cos(om))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) + 1.0*fy*(-px*sin(ka)*cos(fi) + py*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + pz*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)) + tx*sin(ka)*cos(fi) + ty*(sin(fi)*sin(ka)*sin(om) - cos(ka)*cos(om)) + tz*(-sin(fi)*sin(ka)*cos(om) - sin(om)*cos(ka)))*sin(om)*cos(fi)/pow(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om), 2);
j.coeffRef(1,6) = -1.0*fy*(-sin(fi)*sin(ka)*cos(om) - sin(om)*cos(ka))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) - 1.0*fy*(-px*sin(ka)*cos(fi) + py*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + pz*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)) + tx*sin(ka)*cos(fi) + ty*(sin(fi)*sin(ka)*sin(om) - cos(ka)*cos(om)) + tz*(-sin(fi)*sin(ka)*cos(om) - sin(om)*cos(ka)))*cos(fi)*cos(om)/pow(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om), 2);
j.coeffRef(1,7) = -1.0*fy*(py*(-sin(fi)*sin(ka)*cos(om) - sin(om)*cos(ka)) + pz*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + ty*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)) + tz*(sin(fi)*sin(ka)*sin(om) - cos(ka)*cos(om)))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) - 1.0*fy*(py*cos(fi)*cos(om) + pz*sin(om)*cos(fi) - ty*cos(fi)*cos(om) - tz*sin(om)*cos(fi))*(-px*sin(ka)*cos(fi) + py*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + pz*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)) + tx*sin(ka)*cos(fi) + ty*(sin(fi)*sin(ka)*sin(om) - cos(ka)*cos(om)) + tz*(-sin(fi)*sin(ka)*cos(om) - sin(om)*cos(ka)))/pow(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om), 2);
j.coeffRef(1,8) = -1.0*fy*(px*sin(fi)*sin(ka) - py*sin(ka)*sin(om)*cos(fi) + pz*sin(ka)*cos(fi)*cos(om) - tx*sin(fi)*sin(ka) + ty*sin(ka)*sin(om)*cos(fi) - tz*sin(ka)*cos(fi)*cos(om))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) - 1.0*fy*(-px*cos(fi) - py*sin(fi)*sin(om) + pz*sin(fi)*cos(om) + tx*cos(fi) + ty*sin(fi)*sin(om) - tz*sin(fi)*cos(om))*(-px*sin(ka)*cos(fi) + py*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + pz*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)) + tx*sin(ka)*cos(fi) + ty*(sin(fi)*sin(ka)*sin(om) - cos(ka)*cos(om)) + tz*(-sin(fi)*sin(ka)*cos(om) - sin(om)*cos(ka)))/pow(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om), 2);
j.coeffRef(1,9) = -1.0*fy*(-px*cos(fi)*cos(ka) + py*(-sin(fi)*sin(om)*cos(ka) - sin(ka)*cos(om)) + pz*(sin(fi)*cos(ka)*cos(om) - sin(ka)*sin(om)) + tx*cos(fi)*cos(ka) + ty*(sin(fi)*sin(om)*cos(ka) + sin(ka)*cos(om)) + tz*(-sin(fi)*cos(ka)*cos(om) + sin(ka)*sin(om)))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om));
j.coeffRef(1,10) = 1.0*fy*sin(ka)*cos(fi)/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) + 1.0*fy*(-px*sin(ka)*cos(fi) + py*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + pz*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)) + tx*sin(ka)*cos(fi) + ty*(sin(fi)*sin(ka)*sin(om) - cos(ka)*cos(om)) + tz*(-sin(fi)*sin(ka)*cos(om) - sin(om)*cos(ka)))*sin(fi)/pow(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om), 2);
j.coeffRef(1,11) = -1.0*fy*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) - 1.0*fy*(-px*sin(ka)*cos(fi) + py*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + pz*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)) + tx*sin(ka)*cos(fi) + ty*(sin(fi)*sin(ka)*sin(om) - cos(ka)*cos(om)) + tz*(-sin(fi)*sin(ka)*cos(om) - sin(om)*cos(ka)))*sin(om)*cos(fi)/pow(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om), 2);
j.coeffRef(1,12) = -1.0*fy*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka))/(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om)) + 1.0*fy*(-px*sin(ka)*cos(fi) + py*(-sin(fi)*sin(ka)*sin(om) + cos(ka)*cos(om)) + pz*(sin(fi)*sin(ka)*cos(om) + sin(om)*cos(ka)) + tx*sin(ka)*cos(fi) + ty*(sin(fi)*sin(ka)*sin(om) - cos(ka)*cos(om)) + tz*(-sin(fi)*sin(ka)*cos(om) - sin(om)*cos(ka)))*cos(fi)*cos(om)/pow(px*sin(fi) - py*sin(om)*cos(fi) + pz*cos(fi)*cos(om) - tx*sin(fi) + ty*sin(om)*cos(fi) - tz*cos(fi)*cos(om), 2);
}